### ISSUE TITLE
Make bean and property names consistent with the project namespace

### ISSUE THREAD

**Issue by knstvk** [pfurini/cuba-component-user-profile#7]
Would be better to make all prefixes the same as the namespace, e.g.
`nxsecup_UserProfileService`
`nxsecup.hideChangePasswordInSettings`

**Comment by pfurini** [comment]
Hi
yes normally I'd do so, but the reason for that prefixes (for example `ext.security` for properties, and `extsec_` for services) is because this was previously part of a big security component, providing *extensions* to the standard security system.

Then I started dividing it in smaller components. The other one I published is https://github.com/pfurini/cuba-component-forgot-password, and today I'm completing its update for supporting CUBA 6.8.6 (plus adding support for all RDBMS supported by Studio). I'll then submit it to the marketplace too...

It's not uncommon that consumers want both plugins (and other parts that I've not published yet) installed at the same time, and I wanted to maintain a sort of "consistency" with prefixes among them.

Let me know if this makes sense to you, or it is unacceptable for your internal standards.

Thanks,
Paolo

**Comment by pfurini** [comment]
UPDATE: the other component (https://github.com/pfurini/cuba-component-forgot-password) is ready to be submitted to the marketplace as well..

I'm going to wait for clarifications on this issue before doing the submission, though.

Let me know, thx..

**Comment by pfurini** [comment]
@knstvk Sorry to bother you again, but I forgot to mention that these two components are already in use in some third party projects (by CUBA users), and altering the prefixes would be a breaking change in their projects..

**Comment by knstvk** [comment]
OK, if it's on purpose - no problem, let's keep it as it is.
